-- The way in for a player who owns no BIP-39 phrase.
--
--   make -C love2d drive SCRIPT=tests/drive/newwallet.lua
--
-- NEW WALLET → twelve words on screen → three of them typed back from the
-- list → the wallet is used for a real `auth.challenge` / `auth.login`
-- against the server, and the map comes up empty because this account has
-- never existed before.
--
-- The phrase is generated by the OS CSPRNG inside the Rust library, so this
-- script cannot know it in advance — the confirmation steps read it off the
-- scene at the moment they type.

local function scene(name)
  return function(app) return app.scene_name == name end
end

local steps = {}
local function add(t) steps[#steps + 1] = t end

add({ orient = "landscape" })
add({ wait = 0.6 })
add({ until_ = scene("login"), note = "login", timeout = 15 })
add({ shot = "N1-signin.png" })

add({ note = "no phrase? NEW WALLET." })
add({ key = "n" })
add({ until_ = function(app) return app.scene.mode == "new_show" end,
      note = "twelve words generated, on screen", timeout = 10 })
add({ wait = 0.5 })
add({ shot = "N2-write-down.png" })

add({ key = "return" })
add({ until_ = function(app) return app.scene.mode == "new_confirm" end,
      note = "the list is hidden and three words are asked for", timeout = 10 })
add({ wait = 0.4 })
add({ shot = "N3-confirm-empty.png" })

-- A wrong answer first: the confirmation has to actually reject one.
add({ text = "wrong" })
add({ key = "return" })
add({ key = "return" })
add({ text = "also" })
add({ key = "return" })
add({ until_ = function(app)
      return app.scene.mode == "new_confirm" and app.scene.error ~= nil
    end, note = "a wrong word is refused, and says which", timeout = 5 })
add({ wait = 0.4 })
add({ shot = "N4-confirm-wrong.png" })

-- Back to the first field. The wrong attempt left the cursor on the last
-- one, and a script that assumes otherwise types the right words into the
-- wrong boxes — which is what happened the first time this ran.
add({ until_ = function(app)
      if app.scene.answer_focus ~= 1 then love.keypressed("tab") end
      return app.scene.answer_focus == 1
    end, note = "cursor back on the first field", timeout = 5 })

-- Now the right ones, read off the scene the way a player reads their paper.
for i = 1, 3 do
  for _ = 1, 12 do add({ key = "backspace" }) end
  add({ text = function(app) return app.scene.words[app.scene.asked[i]] end })
  if i < 3 then add({ key = "tab" }) end
end
add({ wait = 0.3 })
add({ shot = "N5-confirm-filled.png" })
add({ key = "return" })

add({ until_ = function(app)
      if app.scene_name == "lands" then return true end
      -- Say why, rather than timing out silently.
      print(("waiting: scene=%s mode=%s busy=%s error=%s status=%s"):format(
        tostring(app.scene_name), tostring(app.scene.mode), tostring(app.scene.busy),
        tostring(app.scene.error), tostring(app.scene.status)))
      return false
    end, note = "a brand new account, signed in", timeout = 20 })
add({ wait = 0.8 })
add({ shot = "N6-new-account.png" })

add({ key = "return" })
add({ until_ = scene("categories"), timeout = 10 })
add({ key = "return" })
add({ until_ = function(app) return app.scene_name == "map" and app.scene.nodes end,
      note = "a fresh map: node 1 open, the rest locked", timeout = 10 })
add({ until_ = function(app)
      local open, locked, boss = 0, 0, 0
      for _, n in ipairs(app.scene.nodes) do
        if n.state == "open" then open = open + 1 end
        if n.state == "locked" then locked = locked + 1 end
        if n.kind == "boss" then boss = boss + 1 end
      end
      print(("map: %d nodes, %d open, %d locked, %d boss")
        :format(#app.scene.nodes, open, locked, boss))
      return true
    end, timeout = 5 })
add({ wait = 1.0 })
add({ shot = "N7-fresh-map.png" })

-- The boss node, so the card shows its portrait.
add({ until_ = function(app)
      for i, n in ipairs(app.scene.nodes) do
        if n.kind == "boss" then app.scene.cursor = i; return true end
      end
      return true
    end, timeout = 3 })
add({ wait = 0.8 })
add({ shot = "N8-boss-node.png" })

add({ orient = "portrait" })
add({ resize = { 720, 1000 } })
add({ wait = 1.0 })
add({ shot = "N9-fresh-map-portrait.png" })
add({ quit = true })

return steps
