"""
Read what the shipped fonts can actually draw, into `tests/font-coverage.json`.

    python3 tools/fontcover.py

The sibling LÖVE client has a test called "the fonts cover every language", and
it is the check that stops a translation from silently turning into tofu six
months after somebody adds a string. A browser test cannot read a woff2 `cmap`
— there is no decompressor in the test environment — so the reading happens
here, offline, and the result is committed. `tests/fonts.test.ts` then checks
the six catalogues against it, which means a new string with a character no
shipped font carries fails the suite rather than the player's screen.

Re-run it whenever a font file changes. It needs `fonttools` and `brotli`.
"""

import json
import os
from fontTools.ttLib import TTFont

FONTS = "public/fonts/"
PIXEL = ["PressStart2P-Regular.ttf", "VT323-Regular.ttf"]
CJK = "noto-sans-cjk/NotoSansCJK-Regular.woff2"


def codepoints(path):
    return set(TTFont(FONTS + path, lazy=True).getBestCmap().keys())


def ranges(values):
    """Sorted codepoints as compact hex ranges — 33,000 of them is 2 KB this way."""
    out, s, i = [], sorted(values), 0
    while i < len(s):
        j = i
        while j + 1 < len(s) and s[j + 1] == s[j] + 1:
            j += 1
        out.append(f"{s[i]:X}" if i == j else f"{s[i]:X}-{s[j]:X}")
        i = j + 1
    return out


def main():
    pixel = [codepoints(p) for p in PIXEL]
    both = set.intersection(*pixel)
    either = set.union(*pixel)
    cjk = codepoints(CJK)
    doc = {
        "_": (
            "Generated by tools/fontcover.py — do not edit. Codepoint ranges, hex. "
            "`latin` is what BOTH pixel faces carry, so a string made only of those "
            "is safe in the chrome font and in the body font; `latinAny` is either "
            "of them; `cjk` is the Noto subset."
        ),
        "fonts": {p: os.path.getsize(FONTS + p) for p in PIXEL + [CJK]},
        "latin": ranges(both),
        "latinAny": ranges(either),
        "cjk": ranges(cjk),
    }
    with open("tests/font-coverage.json", "w") as fh:
        json.dump(doc, fh, indent=0)
    print(f"latin {len(both)}  latinAny {len(either)}  cjk {len(cjk)}")


if __name__ == "__main__":
    main()
