import { chromium } from "playwright";
const [OUT, provider, key] = process.argv.slice(2);
const KEY = "4646464646464646464646464646464646464646464646464646464646464646";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.on("pageerror", (e) => console.log("PAGEERROR", e.message));
const buttons = () => page.evaluate(() => window.__cwbCapture.buttons().map((b) => ({ id: b.id, client: b.client, dim: b.dim })));
const click = async (id) => { const b = (await buttons()).find((x) => x.id === id); if (!b) throw new Error(`no ${id}`); await page.mouse.click(b.client[0] + b.client[2] / 2, b.client[1] + b.client[3] / 2); await page.waitForTimeout(500); };
const untilIdle = async () => { const t0 = Date.now(); let idle = 0; while (Date.now() - t0 < 180000) { await page.waitForTimeout(1000); const busy = !((await buttons()).find((b) => b.id === "stop")?.dim ?? true); if (!busy && Date.now() - t0 > 5000 && ++idle > 2) return; } throw new Error("still busy after 3 minutes"); };
await page.goto("http://127.0.0.1:5291/");
await page.waitForFunction(() => window.__cwbCapture?.scene?.() === "login", null, { timeout: 60000 });
await page.locator("textarea.cwb-field").fill(KEY);
await page.locator("textarea.cwb-field").press("ControlOrMeta+Enter");
await page.waitForFunction(() => window.__cwbCapture?.scene?.() === "lands", null, { timeout: 60000 });
await page.evaluate(([p, k]) => { localStorage.setItem(`cwbhacker.ai.key.${p}`, k); localStorage.setItem("cwbhacker.ai.provider", p); }, [provider, key]);
await click("playground");
await page.waitForFunction(() => window.__cwbCapture?.scene?.() === "playground", null, { timeout: 30000 });
await page.waitForTimeout(1500);
await click("new");
await page.waitForTimeout(3000);
await click("agent");
await page.waitForTimeout(1000);
const field = page.locator("input.cwb-agent-field").first();
await field.click();
await page.keyboard.type("Reply with exactly the word: pong");
await page.keyboard.press("Enter");
await untilIdle();
const msgs1 = (await buttons()).filter((b) => b.id.startsWith("msg:")).length;
await field.click();
await page.keyboard.type("a program that prints the sum of 1 to 100");
await click("write");
await untilIdle();
await page.waitForTimeout(500);
const src = await page.evaluate(() => document.querySelector(".cm-content")?.textContent ?? "");
await page.screenshot({ path: `${OUT}/prov-${provider}.png` });
console.log(`${provider}: messages after ask=${msgs1}, editor=${src.length} chars, has sum? ${/5050|1\.\.=100|1\.\.101|sum/.test(src)}`);
await browser.close();
