/**
 * The name a wallet wears until somebody chooses one.
 *
 * An address is 42 characters of hex and that is not a name, and
 * `hacker-58a57e` — the first six of it with a word in front — is the same hex
 * with the same problem. So an account that has not chosen a name gets
 * `AdjectiveNoun####`, derived from the address and from nothing else:
 *
 * ```text
 * hash = keccak256(utf8(lowercase(address)))   // the "0x" is included
 * adj  = uint16(hash[0..2]) % ADJECTIVES.length
 * noun = uint16(hash[2..4]) % NOUNS.length
 * num  = uint16(hash[4..6]) % 10000            // zero-padded to four
 * ```
 *
 * This exists **twice on purpose** — here and in `backend/core/src/username.rs`
 * — because each side needs it at a different moment. The server needs it to
 * name a row nobody seeded; the login screen needs it to show you the name
 * before you have an account to ask about. Both carry the same word lists in
 * the same order and the same four test vectors, and the vectors are what stop
 * the two drifting: the login box would otherwise promise a name the server
 * then disagrees with.
 *
 * The lists are `PocketSkynet-invites`'s, so a player carries one name between
 * the projects. **Order is protocol** — a word inserted anywhere but the end
 * renames every account whose index falls after it, and the lengths are the
 * modulus rather than a fact about the arrays.
 */
import { keccak_256 } from "@noble/hashes/sha3.js";

/** 152 adjectives, in the reference order. */
export const ADJECTIVES: readonly string[] = [
  "Epic",
  "Cyber",
  "Neon",
  "Mystic",
  "Cosmic",
  "Shadow",
  "Phoenix",
  "Quantum",
  "Stellar",
  "Thunder",
  "Blaze",
  "Frost",
  "Storm",
  "Vortex",
  "Turbo",
  "Alpha",
  "Nova",
  "Prism",
  "Apex",
  "Titan",
  "Zephyr",
  "Crimson",
  "Onyx",
  "Jade",
  "Atomic",
  "Binary",
  "Chrome",
  "Digital",
  "Plasma",
  "Sonic",
  "Vector",
  "Hyper",
  "Nano",
  "Omega",
  "Delta",
  "Gamma",
  "Sigma",
  "Zero",
  "Neo",
  "Meta",
  "Pixel",
  "Glitch",
  "Matrix",
  "Neural",
  "Synth",
  "Techno",
  "Vertex",
  "Photon",
  "Solar",
  "Lunar",
  "Arctic",
  "Ember",
  "Aqua",
  "Terra",
  "Volt",
  "Aero",
  "Pyro",
  "Cryo",
  "Inferno",
  "Aurora",
  "Eclipse",
  "Nebula",
  "Typhoon",
  "Tsunami",
  "Magma",
  "Quake",
  "Tidal",
  "Volcanic",
  "Blizzard",
  "Tempest",
  "Savage",
  "Fierce",
  "Swift",
  "Silent",
  "Stealth",
  "Rapid",
  "Prime",
  "Ultra",
  "Mega",
  "Giga",
  "Super",
  "Elite",
  "Royal",
  "Noble",
  "Supreme",
  "Grand",
  "Majestic",
  "Imperial",
  "Dominant",
  "Mighty",
  "Valor",
  "Glory",
  "Arcane",
  "Astral",
  "Ethereal",
  "Void",
  "Dark",
  "Light",
  "Crystal",
  "Golden",
  "Silver",
  "Iron",
  "Steel",
  "Diamond",
  "Ruby",
  "Sapphire",
  "Obsidian",
  "Mythic",
  "Legendary",
  "Ancient",
  "Primal",
  "Divine",
  "Sacred",
  "Cursed",
  "Blessed",
  "Enchanted",
  "Rogue",
  "Rebel",
  "Wild",
  "Feral",
  "Brave",
  "Bold",
  "Daring",
  "Radiant",
  "Blazing",
  "Frozen",
  "Wicked",
  "Chaos",
  "Fury",
  "Venomous",
  "Lethal",
  "Fatal",
  "Deadly",
  "Ruthless",
  "Fearless",
  "Relentless",
  "Azure",
  "Scarlet",
  "Violet",
  "Indigo",
  "Cobalt",
  "Emerald",
  "Amber",
  "Ivory",
  "Ebony",
  "Platinum",
  "Copper",
  "Bronze",
  "Nether",
  "Astro",
  "Galactic",
  "Celestial",
];

/** 156 nouns, in the reference order. */
export const NOUNS: readonly string[] = [
  "Wolf",
  "Hawk",
  "Dragon",
  "Ninja",
  "Samurai",
  "Knight",
  "Ranger",
  "Hunter",
  "Warrior",
  "Guardian",
  "Phantom",
  "Viper",
  "Falcon",
  "Tiger",
  "Panther",
  "Raven",
  "Eagle",
  "Lion",
  "Shark",
  "Fox",
  "Lynx",
  "Cobra",
  "Bear",
  "Leopard",
  "Phoenix",
  "Griffin",
  "Hydra",
  "Kraken",
  "Sphinx",
  "Chimera",
  "Wyvern",
  "Raptor",
  "Basilisk",
  "Cerberus",
  "Leviathan",
  "Fenrir",
  "Pegasus",
  "Minotaur",
  "Gargoyle",
  "Wyrm",
  "Drake",
  "Behemoth",
  "Cyclops",
  "Titan",
  "Scorpion",
  "Mantis",
  "Spider",
  "Jaguar",
  "Puma",
  "Orca",
  "Crow",
  "Owl",
  "Serpent",
  "Python",
  "Mustang",
  "Stallion",
  "Rhino",
  "Gorilla",
  "Wolverine",
  "Badger",
  "Condor",
  "Vulture",
  "Barracuda",
  "Piranha",
  "Mamba",
  "Hornet",
  "Wasp",
  "Beetle",
  "Paladin",
  "Ronin",
  "Shogun",
  "Viking",
  "Spartan",
  "Gladiator",
  "Crusader",
  "Assassin",
  "Sentinel",
  "Warden",
  "Champion",
  "Commander",
  "Captain",
  "Admiral",
  "General",
  "Marshal",
  "Berserker",
  "Centurion",
  "Legionnaire",
  "Templar",
  "Mercenary",
  "Pirate",
  "Bandit",
  "Outlaw",
  "Wizard",
  "Sorcerer",
  "Mage",
  "Warlock",
  "Druid",
  "Shaman",
  "Oracle",
  "Prophet",
  "Reaper",
  "Specter",
  "Wraith",
  "Ghost",
  "Spirit",
  "Demon",
  "Angel",
  "Golem",
  "Necromancer",
  "Alchemist",
  "Enchanter",
  "Summoner",
  "Invoker",
  "Seraph",
  "Valkyrie",
  "Djinn",
  "Blade",
  "Sword",
  "Dagger",
  "Arrow",
  "Bolt",
  "Comet",
  "Meteor",
  "Pulsar",
  "Quasar",
  "Star",
  "Moon",
  "Sun",
  "Flame",
  "Striker",
  "Breaker",
  "Slayer",
  "Hammer",
  "Axe",
  "Spear",
  "Scythe",
  "Trident",
  "Shield",
  "Crown",
  "Throne",
  "Hacker",
  "Cipher",
  "Virus",
  "Coder",
  "Sniper",
  "Gunner",
  "Pilot",
  "Driver",
  "Racer",
  "Runner",
  "Bomber",
  "Tank",
  "Drone",
  "Mech",
  "Android",
  "Cyborg",
];

/**
 * The name this address is known by when nobody has chosen one.
 *
 * Hashes the **address**, never the phrase: the same wallet reached by
 * recovery phrase, by private key, or at a different account index is one
 * account and has to arrive at one name.
 */
export function deterministicUsername(address: string): string {
  const digest = keccak_256(new TextEncoder().encode(address.toLowerCase()));
  const at = (i: number) => (digest[i] << 8) | digest[i + 1];
  const adjective = ADJECTIVES[at(0) % ADJECTIVES.length];
  const noun = NOUNS[at(2) % NOUNS.length];
  const number = String(at(4) % 10000).padStart(4, "0");
  return `${adjective}${noun}${number}`;
}
