-- SPEC §9.1 and §9.2: the LÖVE client must derive the same address and
-- produce the same signature as `CausewaybayWallet` and the browser.
--
-- The fixtures are the shared ones in `tests/vectors/`, generated by QA from
-- the wallet itself — not computed here, because a value this suite computed
-- would only prove that this suite agrees with itself.
--
-- The digest is asserted **separately** from the signature. If the digest
-- matches and the signature does not, the bug is in the curve call; if the
-- digest does not match, the bug is in the message or the length prefix.
-- Splitting them is the difference between a minute and a day.

local T = require("tests.framework")
local wallet = require("src.wallet")
local json = require("src.json")

--- Find `tests/vectors/` from wherever this is being run.
local function vectors_dir()
  -- Built without holes: `ipairs` stops at the first nil, so putting an
  -- unset environment variable first in a literal list silently skips
  -- everything after it.
  local candidates = {}
  local override = os.getenv("CWBH_VECTORS")
  if override and override ~= "" then candidates[#candidates + 1] = override end
  candidates[#candidates + 1] = "../tests/vectors"
  candidates[#candidates + 1] = "tests/vectors"
  candidates[#candidates + 1] = "../../tests/vectors"
  for _, dir in ipairs(candidates) do
    local fh = io.open(dir .. "/addresses.json", "r")
    if fh then fh:close(); return dir end
  end
  return nil
end

local function read_json(path)
  local fh = io.open(path, "r")
  if not fh then return nil end
  local body = fh:read("*a")
  fh:close()
  return json.try_decode(body)
end

return function()
  T.section("wallet — the FFI binding")

  T.case("the search order is named paths only, never a bare library name", function()
    local paths = wallet.search_paths("/game", nil, "OSX")
    for _, p in ipairs(paths) do
      T.ok(p:find("/", 1, true) ~= nil, p .. " must contain a path separator")
    end
    T.eq(paths[1], "/game/libcwbh_ffi.dylib", "a packaged copy beside the game wins")
    T.ok(paths[2]:find("ffi/target/release"), "then a checkout, freshest first")
    -- The application bundle: the executable and the archive both sit one
    -- directory below Contents, and Frameworks is beside them.
    local joined = table.concat(paths, "\n")
    T.ok(joined:find("/Frameworks/libcwbh_ffi.dylib", 1, true) ~= nil,
      "a bundle finds its library in Contents/Frameworks")
    local app = wallet.search_paths("/A.app/Contents/MacOS/love", nil, "OSX")
    local hit = false
    for _, p in ipairs(app) do
      if p == "/A.app/Contents/Frameworks/libcwbh_ffi.dylib" then hit = true end
    end
    T.ok(hit, "from Contents/MacOS/love the path resolves to Contents/Frameworks")
    local override = wallet.search_paths("/game", "/tmp/mine.dylib", "OSX")
    T.eq(override[1], "/tmp/mine.dylib", "CWBH_FFI_LIB beats every guess")
    T.eq(wallet.library_name("Linux"), "libcwbh_ffi.so")
    T.eq(wallet.library_name("Windows"), "cwbh_ffi.dll")
  end)

  T.case("a missing library is a message, not a crash", function()
    local lib, err = wallet.load(nil, "/definitely/not/here/libcwbh_ffi.dylib")
    T.eq(lib, nil)
    T.ok(type(err) == "string" and #err > 0)
    T.ok(err:find("make %-C love2d ffi") ~= nil or err:find("cannot find") ~= nil
      or err:find("ffi") ~= nil, "the message tells the player how to fix it")
    -- And `execute` on a nil library is an error value, not an exception.
    local out, why = wallet.execute(nil, { op = "describe" })
    T.eq(out, nil)
    T.ok(type(why) == "string")
  end)

  T.case("a private key is told apart from a mnemonic by shape", function()
    T.ok(wallet.looks_like_private_key(
      "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"))
    T.ok(wallet.looks_like_private_key(
      "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"))
    T.nope(wallet.looks_like_private_key("0xdeadbeef"))
    T.nope(wallet.looks_like_private_key(
      "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"))
    T.nope(wallet.looks_like_private_key(nil))
  end)

  local lib = wallet.load(os.getenv("CWBH_ROOT") or ".")
  if not lib then
    lib = wallet.load("/Volumes/nvidia/vivid/CausewaybayHacker/love2d")
  end

  if not lib then
    T.skip("wallet — derivation vectors", "libcwbh_ffi is not built: " ..
      tostring(wallet.last_error()):gsub("\n.*", ""))
    return
  end

  T.case("the library reports the ABI this binding expects", function()
    local d = wallet.describe(lib)
    T.ok(d ~= nil)
    T.eq(d.abi, wallet.ABI_VERSION)
    T.eq(d.abi, 6, "6 is the contract with `inflate` in it, for a deflated label")
    T.eq(d.path_template, "m/44'/60'/0'/0/{index}")
    -- A private key and a seed never come back. A generated mnemonic does,
    -- exactly once, and the library says so rather than leaving it implicit.
    T.same(d.never_returns, { "private_key", "seed" })
    T.same(d.returns_key_material_once, { "generate.mnemonic" })
  end)

  T.section("wallet — NEW WALLET, the way in for a first-time player")

  T.case("a generated phrase is twelve valid words with a real address", function()
    local out, err = wallet.generate(lib, 12)
    T.ok(out ~= nil, tostring(err))
    if not out then return end
    T.eq(out.words, 12)
    local words = {}
    for word in out.mnemonic:gmatch("%S+") do words[#words + 1] = word end
    T.eq(#words, 12)
    T.eq(out.path, "m/44'/60'/0'/0/0")
    T.eq(#out.address, 42)
    T.eq(out.address:sub(1, 2), "0x")
    T.eq(wallet.validate(lib, out.mnemonic), true)

    -- The address on the WRITE THIS DOWN screen has to be the account the
    -- player actually logs into, or they write down one wallet and use
    -- another.
    local derived = wallet.derive(lib, out.mnemonic, 0)
    T.eq(derived.address, out.address)
    local signed = wallet.sign(lib, out.mnemonic, 0, "Causewaybay Hacker login\ntest")
    T.eq(signed.address, out.address)
    T.eq(#signed.signature, 132)
  end)

  T.case("two generations never collide", function()
    local seen = {}
    for i = 1, 24 do
      local out = wallet.generate(lib, 12)
      T.ok(out ~= nil)
      if out then
        T.eq(seen[out.mnemonic], nil, ("generation %d repeated an earlier phrase"):format(i))
        seen[out.mnemonic] = true
      end
    end
  end)

  T.case("the phrase is the only key material that ever comes back", function()
    -- `generate` is the one sanctioned exception (love2d/ffi/src/lib.rs), and
    -- it is bounded: a phrase, and things derived from it that are safe to
    -- show. No private key, no seed, in this response or any other.
    local out = wallet.generate(lib, 12)
    T.ok(out ~= nil)
    local keys = {}
    for k in pairs(out) do keys[#keys + 1] = k end
    table.sort(keys)
    T.same(keys, { "address", "address_lower", "mnemonic", "ok", "path", "words" })
    -- And the phrase really is a phrase, not a key.
    T.nope(wallet.looks_like_private_key(out.mnemonic))
  end)

  T.case("secure sets 0700 on a directory and 0600 on a file", function()
    -- SPEC §1.1. Not cryptography — it is here because LÖVE has no `chmod`
    -- and `src/store.lua` writes a file holding a session token.
    local base = os.getenv("TMPDIR") or "/tmp"
    local dir = ("%s/cwbh-secure-%d"):format(base:gsub("/$", ""), os.time())
    local ok, mode = wallet.secure(lib, dir, true)
    T.eq(ok, true, tostring(mode))
    T.eq(mode, "700")

    local file = dir .. "/state.jsonl"
    local fh = io.open(file, "w")
    T.ok(fh ~= nil)
    if fh then fh:write("{}\n"); fh:close() end
    local fok, fmode = wallet.secure(lib, file, false)
    T.eq(fok, true, tostring(fmode))
    T.eq(fmode, "600")

    -- And it really is on disk, not just reported.
    local listed = io.popen(("ls -ld %q %q 2>/dev/null"):format(dir, file))
    local text = listed and listed:read("*a") or ""
    if listed then listed:close() end
    T.ok(text:find("drwx------", 1, true) ~= nil, "the directory is 0700: " .. text)
    T.ok(text:find("-rw-------", 1, true) ~= nil, "the file is 0600: " .. text)
    os.remove(file)
    os.execute(("rmdir %q 2>/dev/null"):format(dir))
  end)

  T.case("secure refuses a missing path rather than pretending", function()
    local ok, err = wallet.secure(lib, "", false)
    T.eq(ok, false)
    T.ok(type(err) == "string")
    local ok2, err2 = wallet.secure(lib, "/definitely/not/here/state.jsonl", false)
    T.eq(ok2, false)
    T.ok(type(err2) == "string" and err2:find("state.jsonl") ~= nil)
  end)

  T.case("a word count BIP-39 does not have is refused, with no phrase", function()
    local out, err = wallet.generate(lib, 13)
    T.eq(out, nil)
    T.ok(type(err) == "string" and err:find("13") ~= nil)
  end)

  local dir = vectors_dir()
  if not dir then
    T.skip("wallet — shared vectors", "tests/vectors/ not found from here")
    return
  end

  T.section("wallet — §9.1 address conformance (tests/vectors/addresses.json)")

  local addresses = read_json(dir .. "/addresses.json")
  T.case("addresses.json loads and names the path this client uses", function()
    T.ok(addresses ~= nil)
    T.eq(addresses.path_template, "m/44'/60'/0'/0/{index}")
  end)

  if addresses then
    local count = 0
    for _, entry in ipairs(addresses.mnemonics) do
      T.case(("%s — %d accounts"):format(entry.name, #entry.accounts), function()
        for _, account in ipairs(entry.accounts) do
          local got, err = wallet.derive(lib, entry.phrase, account.index)
          T.ok(got ~= nil, tostring(err))
          if got then
            T.eq(got.address, account.address,
              ("%s index %d: EIP-55 address"):format(entry.name, account.index))
            T.eq(got.address_lower, account.address_lower, "SPEC §3.4's lowercase form")
            T.eq(got.public_key_compressed, account.public_key_compressed)
            T.eq(got.path, account.path)
            count = count + 1
          end

          -- The same account reached from the raw private key must agree:
          -- SPEC §3.1 says a private key "skips straight to the last arrow".
          local by_key = wallet.derive(lib, account.private_key, 0)
          T.ok(by_key ~= nil)
          if by_key then
            T.eq(by_key.address, account.address, "a raw private key gives the same address")
          end
        end
      end)
    end
    T.case("every account in the fixture was checked", function()
      T.ok(count >= 10, ("checked %d accounts"):format(count))
    end)
  end

  T.section("wallet — §9.2 signature conformance (tests/vectors/signatures.json)")

  local signatures = read_json(dir .. "/signatures.json")
  T.case("signatures.json loads, and its message is the §4.2 four-liner", function()
    T.ok(signatures ~= nil)
    if signatures then
      T.eq(signatures.message_template.trailing_newline, false)
      T.eq(signatures.message_template.joined_by, "\\n")
    end
  end)

  if signatures then
    for _, v in ipairs(signatures.vectors) do
      T.case(v.name .. " — digest", function()
        -- Half one: the EIP-191 digest, on its own.
        local got, err = wallet.eip191(lib, v.message)
        T.ok(got ~= nil, tostring(err))
        if got then
          T.eq(got.message_len, v.message_len,
            "the length prefix counts bytes, not characters")
          T.eq(got.digest, v.eip191_digest)
        end
        -- The fixture's own hex is the byte-for-byte truth about the message.
        local hexed = "0x" .. v.message:gsub(".", function(c)
          return string.format("%02x", c:byte())
        end)
        T.eq(hexed, v.message_hex, "the message this client signs is the one in the fixture")
      end)

      T.case(v.name .. " — signature", function()
        -- Half two: the curve.
        local got, err = wallet.sign(lib, v.private_key, 0, v.message)
        T.ok(got ~= nil, tostring(err))
        if got then
          T.eq(got.address, v.address)
          T.eq(got.digest, v.eip191_digest)
          T.eq(got.signature, v.signature, "r || s || v, 65 bytes, hex")
          T.eq(#got.signature, 132, "0x + 130 hex (§4.3)")
          T.eq(got.r, v.r)
          T.eq(got.s, v.s)
          -- The fixture is emphatic about this one: k256's RecoveryId is
          -- 0/1, the wire wants 27/28. A client that ships the wrong one
          -- fails every login.
          T.eq(got.v, v.v, "v is the Ethereum 27/28 form on the wire")
          T.eq(got.recovery_id, v.recovery_id, "and the k256 0/1 form beside it")
          T.eq(got.v, got.recovery_id + 27)
        end
      end)
    end

    T.case("signing is deterministic (RFC 6979), so a retry gives the same bytes", function()
      local v = signatures.vectors[1]
      local a = wallet.sign(lib, v.private_key, 0, v.message)
      local b = wallet.sign(lib, v.private_key, 0, v.message)
      T.eq(a.signature, b.signature)
    end)

    T.case("a mnemonic and its private key sign identically", function()
      -- The address fixture's account 0 is the signature fixture's second
      -- vector, so the two files have to agree through this client.
      local entry = addresses.mnemonics[1]
      local account = entry.accounts[1]
      local message = "Causewaybay Hacker login\naddress: " .. account.address
        .. "\nnonce: " .. string.rep("ab", 32)
        .. "\nexpires: 2026-09-11T04:14:33Z"
      local by_phrase = wallet.sign(lib, entry.phrase, 0, message)
      local by_key = wallet.sign(lib, account.private_key, 0, message)
      T.eq(by_phrase.signature, by_key.signature)
      T.eq(by_phrase.address, account.address)
    end)
  end

  T.section("wallet — §8.5, from the other side of the ABI")

  T.case("no response from the library ever contains key material", function()
    local phrase =
      "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
    local key = "0x1ab42cc412b618bdea3a599e3c9bae199ebf030895b039e9db1e30dafb12b727"
    for _, req in ipairs({
      { op = "derive", mnemonic = phrase, index = 0 },
      { op = "sign", mnemonic = phrase, index = 0, message = "hello" },
      { op = "sign", private_key = key, message = "hello" },
      { op = "validate", mnemonic = phrase },
      { op = "describe" },
    }) do
      local out = wallet.execute(lib, req)
      local text = out and json.encode(out) or ""
      T.nope(text:find("abandon", 1, true), "no mnemonic in a response")
      T.nope(text:find(key:sub(3), 1, true), "no private key in a response")
    end
  end)

  T.case("a bad mnemonic is refused with a reason that does not name the word", function()
    local ok, reason = wallet.validate(lib,
      "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon")
    T.eq(ok, false)
    T.ok(reason:find("checksum") ~= nil)

    local ok2, reason2 = wallet.validate(lib,
      "zzzz abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about")
    T.eq(ok2, false)
    T.ok(reason2:find("word 1 of 12") ~= nil, "the position, not the word")
    T.nope(reason2:find("zzzz", 1, true))
  end)

  T.case("an unknown op is an error value rather than a crash", function()
    local out, err = wallet.execute(lib, { op = "give_me_the_key" })
    T.eq(out, nil)
    T.ok(err:find("give_me_the_key") ~= nil)
  end)
end
